### ISSUE TITLE
1.0.14 Error: 'realpath'

### ISSUE THREAD

**Issue by fjbanares** [pantulis/tacoma#18]
After updating to 1.0.14, with Ruby 2.1.2 raise this error:

```
/home/faustobanares/.rvm/gems/ruby-2.1.2@edo-entradas/gems/tacoma-1.0.14/lib/tacoma/command.rb:162:in `build_template_path': undefined method `realpath' for #<String:0x00000002a7b050> (NoMethodError)
	from /home/faustobanares/.rvm/gems/ruby-2.1.2@edo-entradas/gems/tacoma-1.0.14/lib/tacoma/command.rb:110:in `block in switch'
	from /home/faustobanares/.rvm/gems/ruby-2.1.2@edo-entradas/gems/tacoma-1.0.14/lib/tacoma/command.rb:109:in `each'
	from /home/faustobanares/.rvm/gems/ruby-2.1.2@edo-entradas/gems/tacoma-1.0.14/lib/tacoma/command.rb:109:in `switch'
	from /home/faustobanares/.rvm/gems/ruby-2.1.2@edo-entradas/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /home/faustobanares/.rvm/gems/ruby-2.1.2@edo-entradas/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/faustobanares/.rvm/gems/ruby-2.1.2@edo-entradas/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /home/faustobanares/.rvm/gems/ruby-2.1.2@edo-entradas/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /home/faustobanares/.rvm/gems/ruby-2.1.2@edo-entradas/gems/tacoma-1.0.14/bin/tacoma:4:in `<top (required)>'
	from /home/faustobanares/.rvm/gems/ruby-2.1.2@edo-entradas/bin/tacoma:23:in `load'
	from /home/faustobanares/.rvm/gems/ruby-2.1.2@edo-entradas/bin/tacoma:23:in `<main>'
	from /home/faustobanares/.rvm/gems/ruby-2.1.2@edo-entradas/bin/ruby_executable_hooks:15:in `eval'
	from /home/faustobanares/.rvm/gems/ruby-2.1.2@edo-entradas/bin/ruby_executable_hooks:15:in `<main>'
```

Nothing changed in tacoma files between 1.0.13 and this new version.
